const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sproutg', {
  getSettings: () => ipcRenderer.invoke('sproutg:get-settings'),
  setSetting: (partial) => ipcRenderer.invoke('sproutg:set-setting', partial),
  openSettings: () => ipcRenderer.invoke('sproutg:open-settings'),
  openStats: () => ipcRenderer.invoke('sproutg:open-stats'),
  openCompany: () => ipcRenderer.invoke('sproutg:open-company'),
  openBridgeLogin: () => ipcRenderer.invoke('sproutg:open-bridge-login'),
  reconnectBridge: () => ipcRenderer.invoke('sproutg:reconnect-bridge'),
  reloadWeb: () => ipcRenderer.invoke('sproutg:reload-web'),
  windowControl: (action) => ipcRenderer.send('sproutg:window-control', action),
  getUpdateState: () => ipcRenderer.invoke('sproutg:get-update-state'),
  getPoints: () => ipcRenderer.invoke('sproutg:get-points'),
  checkForUpdates: () => ipcRenderer.invoke('sproutg:check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('sproutg:download-update'),
  installUpdate: () => ipcRenderer.invoke('sproutg:install-update'),
  getRollbackInfo: () => ipcRenderer.invoke('sproutg:get-rollback-info'),
  rollbackUpdate: () => ipcRenderer.invoke('sproutg:rollback-update'),
  heroSms: (action, payload) => ipcRenderer.invoke('sproutg:hero-sms', action, payload),
  apiCall: (action, payload, opts) => ipcRenderer.invoke('sproutg:api-call', action, payload, opts),
  apiBatch: (calls, opts) => ipcRenderer.invoke('sproutg:api-batch', calls, opts),
  legacyCall: (action, payload, opts) => ipcRenderer.invoke('sproutg:legacy-call', action, payload, opts),
  getBridgeState: () => ipcRenderer.invoke('sproutg:bridge-state'),
  getStorageIntegrity: () => ipcRenderer.invoke('sproutg:get-storage-integrity'),
  retryBlockedWrites: (writeIds) => ipcRenderer.invoke('sproutg:write-queue-retry-blocked', writeIds),
  archiveBlockedWrites: (writeIds) => ipcRenderer.invoke('sproutg:write-queue-archive-blocked', writeIds),
  completeWriteBarrier: (payload) => ipcRenderer.send('sproutg:write-barrier-result', payload),
  postWebMessage: (msg) => ipcRenderer.send('sproutg:web-message', msg),
  onUpdateState: (cb) => ipcRenderer.on('sproutg:update-state', (_e, payload) => cb(payload)),
  onNotice: (cb) => ipcRenderer.on('sproutg:notice', (_e, payload) => cb(payload)),
  onBridgeState: (cb) => ipcRenderer.on('sproutg:bridge-state', (_e, payload) => cb(payload)),
  onStorageIntegrity: (cb) => ipcRenderer.on('sproutg:storage-integrity', (_e, payload) => cb(payload)),
  onPrepareWriteBarrier: (cb) => ipcRenderer.on('sproutg:prepare-write-barrier', (_e, payload) => cb(payload)),
  onReleaseWriteBarrier: (cb) => ipcRenderer.on('sproutg:release-write-barrier', () => cb()),
  onThemeColors: (cb) => ipcRenderer.on('sproutg:theme-colors', (_e, payload) => cb(payload)),
  onPointsUpdated: (cb) => ipcRenderer.on('sproutg:points-updated', (_e, payload) => cb(payload)),
  onPointsDelta: (cb) => ipcRenderer.on('sproutg:points-delta', (_e, payload) => cb(payload)),
  onApplySettings: (cb) => ipcRenderer.on('sproutg:apply-settings', (_e, settings) => cb(settings))
});
